# Generated by Django 3.0.5 on 2020-04-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
