# Generated by Django 3.0.5 on 2020-04-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200412_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='book',
        ),
        migrations.RemoveField(
            model_name='business',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
