# Generated by Django 3.0.5 on 2020-04-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200427_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('m_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(default=0)),
                ('m_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='parts',
            field=models.ManyToManyField(through='polls.WorkshopPart', to='polls.Part'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('worktype', models.CharField(max_length=200)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehousePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='parts',
            field=models.ManyToManyField(through='polls.WarehousePart', to='polls.Part'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(through='polls.WarehouseProduct', to='polls.Product'),
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Workshop'),
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(through='polls.ProductPart', to='polls.Part'),
        ),
    ]
